### PR TITLE
Small fix for 8chan

### PR DESCRIPTION
**Pull request by bbblitz**
Fixed include for 8chan, and included it's alternate domain, hatechan

### CODE REVIEW

**Comment by desudesutalk** [comment]
Why we need this - `https://8chan.co/*/*/*`? Where we have third level?

From my understanding `https://8chan.co/*/*` is enough as it covers everything starting from `https://8chan.co/ddt/index.html`, then `https://8chan.co/ddt/res/1839.html` and everything what is deeper than that.

**Comment by desudesutalk** [comment]
Ah! I think i understand now.

You want DDT to stop from working on `https://8chan.co/ddt/index.html`? But why? From this page you can create thread from DDT (so op-image shows what this is your thread for example) or you can scan threads in `https://8chan.co/b/index.html`, then wait several minutes, hit `F5` and scan again.

I think we should not remove this possibilities from script.

By the way - what is other 8chan clone what is part of 2ch? I think it should be also added as it uses same platform, so DDT will work there also.

**Comment by bbblitz** [comment]
Well, when I saw ```8chan.co/*/*```, I assumed that it was only meant to work in the reply page, since if it was meant to work on just 8chan.co/ddt/ the extra ```/*``` would be unnecessary, but I think I understand you now, and it's meant to be ```8chan.co/*```, hatechan.co is an alternate domain name for 8chan, but masks the url.

**Comment by desudesutalk** [comment]
Ok, i close this Pull now. I just updated includes in DDT.

**Pull request closed without merging**
